      serve:
        admin:
          host: 0.0.0.0
          cors:
            allowed_origins:
              - "*"
            allowed_methods:
              - POST
            allowed_headers:
              - "Authorization,Content-Type"
            exposed_headers:
              - "Content-Type"
            allow_credentials: false
            options_passthrough: false
            max_age: 0
            debug: false
            enabled: true
          socket:
            group: ""
            mode: 0
            owner: ""
          access_log:
            disable_for_health: false
          tls:
            cert:
              path: /app/cert.pem
            allow_termination_from:
              - 127.0.0.1/32
            enabled: true
            key:
              path: /app/key.pem
          port: 4445
        tls:
          cert:
            path: /app/cert.pem
          allow_termination_from:
            - 127.0.0.1/32
          key:
            path: /app/key.pem
        cookies:
          same_site_legacy_workaround: true
          same_site_mode: Strict
        public:
          host: localhost
          cors:
            allowed_origins:
              - "*"
            allowed_methods:
              - POST
            allowed_headers:
              - ""
            exposed_headers:
              - ""
            allow_credentials: false
            options_passthrough: false
            max_age: 0
            debug: false
            enabled: false
          socket:
            group: ""
            mode: 0
            owner: ""
          access_log:
            disable_for_health: false
          tls:
            cert:
              path: /app/cert.pem
            allow_termination_from:
              - 127.0.0.1/32
            key:
              path: /app/key.pem
          port: 1
      dsn: ""
      hsm:
        library: ""
        pin: ""
        slot: -100000000
        token_label: ""
        key_set_prefix: ""
        enabled: false
      webfinger:
        oidc_discovery:
          token_url: https://localhost/oauth2/token
          auth_url: https://localhost/oauth2/auth
          client_registration_url: https://localhost/clients
          supported_claims:
            - email
            - username
          supported_scope:
            - email
          userinfo_url: https://localhost/my-custom-userinfo-endpoint
          jwks_url: https://localhost/.well-known/jwks.json
        jwks:
          broadcast_keys: 
             - hydra.jwt.access-token
      oidc:
        dynamic_client_registration:
          default_scope:
            - openid
            - offline
            - offline_access
          enabled: false
        subject_identifiers:
          supported_types:
            - public
            - pairwise
          pairwise:
            salt: some-random-salt
      urls:
        login: https://localhost/auth/login
        consent: https://localhost/auth/consent
        logout: https://localhost/auth/logout
        error: https://localhost/auth/error
        post_logout_redirect: https://localhost/app/logout-successful
        self:
          public: https://localhost:4444/
          issuer: https://localhost:4444/
      strategies:
        access_token: opaque
        scope: exact
      ttl:
        access_token: 1h
        refresh_token: 1h
        id_token: 1h
        auth_code: 1h
        login_consent_request: 1h
      oauth2:
        session:
          encrypt_at_rest: true
        include_legacy_error_fields: true
        exclude_not_before_claim: true
        allowed_top_level_claims:
          - username
          - email
          - user_uuid
        hashers:
          bcrypt:
            cost: 10
        pkce:
          enforced_for_public_clients: true
          enforced: true
        client_credentials:
          default_grant_allowed_scope: false
        grant:
          jwt:
            iat_optional: false
            max_ttl: 1h
            jti_optional: false
        refresh_token_hook: https://localhost/auth/token-refresh-hook
        expose_internal_errors: true
      secrets:
        cookie:
          - this-is-the-primary-secret
          - this-is-an-old-secret
          - this-is-another-old-secret
        system:
          - this-is-the-primary-secret
          - this-is-an-old-secret
          - this-is-another-old-secret
      profiling: cpu
      tracing:
        service_name: Example Service
        providers:
          zipkin:
            server_url: http://localhost:9411/api/v2/spans
          jaeger:
            propagation: jaeger
            max_tag_value_length: 0
            sampling:
              type: const
              value: 1
              server_url: http://localhost:5778/sampling
            local_agent_address: 127.0.0.1:6831
        provider: jaeger
      sqa:
        opt_out: true
      version: v0.0.0
      cgroups:
        v1:
          auto_max_procs_enabled: true
      dangerous-force-http: false
      dangerous-allow-insecure-redirect-urls:
      log:
        leak_sensitive_values: true
        redaction_text: ""
        format: text
        level: trace